repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
  - id: ruff-check
    args: [ --fix, --exit-non-zero-on-fix , --show-fixes]
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    exclude: \.md$

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: bash -c "cd $(git rev-parse --show-toplevel) && poetry run mypy --config-file=mypy.ini --namespace-packages src/"
    require_serial: true
    language: python
    types: [ python ]

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true

