# Generated by Django 5.2.7 on 2025-10-17 02:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlystatemententity",
            old_name="transations",
            new_name="transactions",
        ),
        migrations.AlterField(
            model_name="bookletaccountentity",
            name="account_number",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name="bookletaccountentity",
            unique_together={("entity_id", "account_number")},
        ),
    ]
