# Generated by Django 5.2.7 on 2025-10-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bank_app",
            "0002_rename_transations_monthlystatemententity_transactions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccountentity",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bankaccountentity",
            name="overdraft_amount",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bookletaccountentity",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bookletaccountentity",
            name="deposit_limit",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="monthlystatemententity",
            name="closing_balance",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="monthlystatemententity",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transationentity",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transationentity",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
