# Generated by Django 5.2.7 on 2025-10-18 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0003_alter_bankaccountentity_balance_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankaccountentity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="bookletaccountentity",
            unique_together=set(),
        ),
    ]
