# Generated by Django 5.2.7 on 2025-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0004_alter_bankaccountentity_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transationentity",
            name="balance_after",
        ),
        migrations.AddField(
            model_name="transationentity",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CURRENT_ACCOUNT", "CURRENT_ACCOUNT"),
                    ("BOOKLET_ACCOUNT", "BOOKLET_ACCOUNT"),
                ],
                default="CURRENT_ACCOUNT",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="transationentity",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("WITHDRAWAL", "WITHDRAWAL"),
                    ("DEPOSIT", "DEPOSIT"),
                    ("TRANSFER", "TRANSFER"),
                ],
                max_length=25,
            ),
        ),
    ]
