# Generated by Django 5.2.7 on 2025-10-20 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0005_remove_transationentity_balance_after_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transationentity",
            old_name="transation_date",
            new_name="transaction_date",
        ),
    ]
