# Generated by Django 5.2.7 on 2025-10-21 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0006_rename_transation_date_transationentity_transaction_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransationEntity",
            new_name="TransactionEntity",
        ),
    ]
